### ISSUE TITLE
parse_theory

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#18]
It would be nice to have a function that parses a theory as a string and produces a TheoryParser. A version of this is on the test files, but it would be worth it to make it available on the package.

https://github.com/potassco/python-clingox/blob/ef384c886fac2d1752828db28382c14ae233de3c/clingox/tests/test_ast.py#L121

Perhaps just adding some error check to this function is enough.

**Comment by rkaminsk** [comment]
If you find this function useful, we can move it into the ast module. Regarding error handling, we should probably ensure that there is exactly one TheoryDefinition in the string (ignoring the implicit base program block).
