### ISSUE TITLE
Parsing theory atoms as conditional literals

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#19]
Eclingo has a function that theory atoms as literals. This function could be generalized to parse some theory atoms  as lists of conditional literals. For instance, we could parse

&t{ a(X) : b(X) ; not c(Y) : d(Y) }

as lists of conditional literals "[ t_a(X) : b(X), not t_c(Y) : d(Y) ]" or "[ t(a(X)) : b(X), not t(c(Y)) : d(Y) ]".

Let me know if this would be considered interested for other applications.

**Comment by rkaminsk** [comment]
This looks rather specific. What might of more general interest are functions to convert theory terms to literals or normal terms on the AST level. This would make it easy to implement your usecase.

**Comment by jorgefandinno** [comment]
Ok, that is actually the function that eclingo has. I will pulled it out and polish it a bit.
