### ISSUE TITLE
Make compatible with clingo 5.5

### ISSUE THREAD

**Issue by rkaminsk** [potassco/python-clingox#21]
@jorgefandinno, the latest wip branch is only compatible with the latest clingo wip branch. Since the next clingo release might still take a while, clingox should be made backward compatible. We can simply lower the version requirement and disable some tests for older clingo versions (see 6427c7e8d60bea97912f6b32a4c9d75454a1ab98).

**Comment by jorgefandinno** [comment]
It make sense. It seems that changes relate with the ast of comparisons and csps?
This should cause no much trouble.
