### ISSUE TITLE
static method

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#24]
This could be a static method or a jjust a function

https://github.com/potassco/python-clingox/blob/279f35bad138ee06f7e4f63feaafb54f1083fef5/clingox/theory.py#L132

**Comment by rkaminsk** [comment]
The function is meant to be overridable to implement further operators. This would not work with a static method.

**Comment by jorgefandinno** [comment]
Can we put ````pylint: disable=no-self-use``` because ```pylint 2.13.9``` reports it as a error.

**Comment by rkaminsk** [comment]
> Never mind, new version of pylint ignores the warning.

This is checked by a plugin/extension. The current configuration does not load any plugins. Check the `load-plugins=` line in the config file in the project rule.

https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/no-self-use.html
