### ISSUE TITLE
ast.get_body()

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#33]
I have been using ```ast.get_body()``` in eclingo to replace some custom functions and I was able to do all I wanted. Still, I found the interface a bit cumberston. In particular, when combining this function with other transformations, I found myself having to create fake rules just to apply the function to its body, which at this point was just a list of ASTs.

May be it would make sense to change the interface
```python
def get_body(stm: AST,...)
```
by
```python
def filter_body(body: Iterable[AST],...)
```
Then, the old functionality is easy definable by
```python
def get_body(stm: AST,...)
    return filter_body(stm.body,...)
```
Opinions?

**Comment by rkaminsk** [comment]
Just go ahead and change it to what you require. It's your function. :smile:
