### ISSUE TITLE
Program not gringo parsable

### ISSUE THREAD

**Issue by jorgefandinno** [potassco/python-clingox#38]
Weight rules as printed by ```_pretty_str_weight_rule``` are not gringo parsable.

For instance, 
```bash
$gringo --version
gringo version 5.6.1
Address model: 64-bit

libgringo version 5.6.1
Configuration: with Python 3.9.13, without Lua
License: The MIT License <https://opensource.org/licenses/MIT>

$echo "{a} :- 10{7,0: b, 5,1: not c}." | gringo
-:1:12-13: error: syntax error, unexpected ","

*** ERROR: (gringo): parsing failed
```

This rule appears this way in the tests.
https://github.com/potassco/python-clingox/blob/4089afed444e9e6ddea9d03092e2903680f1d748/clingox/tests/test_program.py#L251

Should this rule be wrote be ```{a} :- 10#sum{7,0: b; 5,1: not c}.``` It misses the ```#sum``` and uses comma instead of semicolon.

Also both ```test_add_weight_rule``` and ```test_add_weight_choice_rule``` test a choice rule. Shouldn't one test a normal rule?

**Comment by rkaminsk** [comment]
Looks like a bug. There should really be a semicolon.
