### ISSUE TITLE
Documentation bug: clingox.backend

### ISSUE THREAD

**Issue by Entze** [potassco/python-clingox#43]
In the documentation of `clingox.backend` there is a bug in the module description, specifically in the example (`backend.py` lines 15-24)

Line 16 reads 
```python
from clingox.backends import SymbolicBackend
```

that should probably read

```python
from clingox.backend import SymbolicBackend
```
(without the s)

as the file is called `backend.py` and not `backends.py`.

**Comment by rkaminsk** [comment]
Thanks, will be fixed with the next clingox relase.
